"""search migration2

Revision ID: 4ee4fb2db618
Revises: 19bd83ba3b8f
Create Date: 2025-11-20 18:00:50.764127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee4fb2db618'
down_revision = '19bd83ba3b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_text', sa.String(length=255), nullable=False))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('search_text')

    # ### end Alembic commands ###
